<?php

namespace FilePatchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DavRepository extends EntityRepository
{
}
