<?php

namespace FilePatchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatchRepository extends EntityRepository
{
}
